-- 清徽半导体材料 MySQL 初始化脚本
CREATE DATABASE IF NOT EXISTS vvnano CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'vvnano'@'%' IDENTIFIED BY 'vvnano2025';
GRANT ALL PRIVILEGES ON vvnano.* TO 'vvnano'@'%';
FLUSH PRIVILEGES;
